# Generated by Django 4.2.9
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyapp', '0001_initial'),  # แก้ไขเป็นชื่อแอพของคุณและ migration ก่อนหน้า
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, verbose_name='ที่อยู่'),
        ),
        migrations.AddField(
            model_name='person',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=13, verbose_name='เลขบัตรประชาชน'),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(default='ไทย', max_length=50, verbose_name='สัญชาติ'),
        ),
        migrations.AlterField(
            model_name='person',
            name='concrete_mixer_numbers',
            field=models.CharField(blank=True, max_length=100, verbose_name='เลขประจำรถโม่'),
        ),
        migrations.AlterField(
            model_name='person',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ค่าจ้างต่อวัน'),
        ),
    ]