# Generated by Django 5.2 on 2025-05-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.AddField(
            model_name='person',
            name='Role',
            field=models.CharField(choices=[('Employee', 'พนักงานทั่วไป'), ('Accountant', 'พนักงานบัญชี'), ('Concrete Mixer Driver', 'คนขับรถโม่'), ('Production staff', 'พนักงานฝ่ายผลิต'), ('Plant Operator', 'คนดูแลแพ้นท์'), ('Leader Employee', 'หัวหน้าพนักงาน')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
