# Generated by Django 5.2 on 2025-05-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_fee_delete_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(0, 'ไม่ได้ทำงาน'), (1, 'ทำงาน')], default=1),
        ),
    ]
