# Generated by Django 5.2 on 2025-05-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='extra_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
