# Generated by Django 5.2 on 2025-05-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_salaryrecord_extra_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='extra_expenses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
