# Generated by Django 5.2 on 2025-05-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_salaryrecord_extra_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='remaining',
        ),
    ]
