# Generated by Django 5.2 on 2025-05-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_activitylog_alter_workday_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='เบอร์โทรศัพท์'),
        ),
    ]
